# Generated by Django 5.2.7 on 2025-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
