# Generated by Django 5.2.7 on 2025-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_block_user", "Сan block user"),
                    ("can_manage_users", "Can_manage_users"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
