# Generated by Django 5.2.7 on 2025-11-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Рассылка активна"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="sent_messages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailing",
            name="successful_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailing",
            name="unsuccessful_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
