# Generated by Django 5.2.7 on 2025-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_mailing_is_active_mailing_sent_messages_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_disable_mailing", "Can disable mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing_attempt",
            options={
                "ordering": ["status"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
