# Generated by Django 5.2.7 on 2025-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_mailing_options_alter_mailing_attempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="sent_messages",
            field=models.IntegerField(default=0, verbose_name="Сообщений отправлено"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="successful_attempts",
            field=models.IntegerField(default=0, verbose_name="Успешные попытки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="unsuccessful_attempts",
            field=models.IntegerField(default=0, verbose_name="Неуспешные попытки"),
        ),
    ]
