# Generated by Django 5.2.7 on 2025-11-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_message_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="sent_messages",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="successful_attempts",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="unsuccessful_attempts",
        ),
    ]
