# Generated by Django 5.2.7 on 2025-11-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_remove_mailing_sent_messages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing_attempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_attempt_set",
                to="newsletter.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
